const ROLES = {
  USER: 'ROLE_USER',
  ADMIN: 'ROLE_ADMIN',
  ORGANIZATION_ADMIN: 'ROLE_ORG_ADMIN',
  SPORTS_CENTER_ADMIN: 'ROLE_SPORTS_CENTER_ADMIN',
  FPA_ADMIN: 'ROLE_FPA_ADMIN',
};


module.exports = {
  ROLES
};
